#!/bin/bash -e

# TODO: We may need to install a different bash completion
# depending on bash version.

for item in $(/bin/ls -1 config_files)
do
    /bin/rm -rf ~/.$item
    ln -s `pwd`/config_files/$item ~/.$item
done

chmod -R g-rwx ~/.ssh
chmod -R o-rwx ~/.ssh

chmod -R g-rwx ~/shell_config
chmod -R o-rwx ~/shell_config

chgrp -R jgfouca ~/shell_config
chgrp -R jgfouca ~/.ssh
